baseURL: 'http://personalsitejoeheflin.s3-website.us-east-2.amazonaws.com/' # if your site is in 'https', then make sure youp' otherwise yr base url isn't written using 'httour sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: Welcome
paginate: 5
theme: charlolamode

params:
    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Joe Heflin
        description: |
    
          Hi, my name is Joe.
          I enjoy solving problems using software. 
        
    
          This is my personal website built using the Hugo framework and hosted statically in AWS s3.
        imageUrl: "static/images/profile.png"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        # buttons:
        #     - name: Don't click me
        #       url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
