baseURL: 'http://joeheflin.com/' # if your site is in 'https', then make sure youp' otherwise yr base url isn't written using 'httour sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: Joe Heflin
paginate: 5
theme: charlolamode

menu:
    main:
        - name: Contact Me
          url: /contact/
          weight: 30
        - name: Background
          url: /resume/
          weight: 25
        # - name: Projects
        #   url: /projects/
        #   weight: 27

params:
    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Hello
        description: |
    
          My name is Joe.
          I have a passion for creating solutions and architecting robust systems using software. 
          Welcome to my personal website.
          
        imageUrl: "images/joepic.jpg"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
        #     - name: Don't click me
        #       url: https://www.youtube.com/watch?v=dQw4w9WgXcQ

    socialIcons:
        # - name: buymeacoffee
        #   url: "https://ko-fi.com/heycharlola"
        - name: github
          url: "https://github.com/JoeHeflin"
        - name: linkedin
          url: "https://www.linkedin.com/in/joseph-heflin/"

          # change favicon in images folder (icon for web tab)
    assets:
    #       favicon: "/images/favicon.ico"
    #       favicon16x16: "/images/favicon-16x16.png"
    #       favicon32x32: "/images/favicon-32x32.png"
    #       apple_touch_icon: "/images/apple-touch-icon.png"
    #       safari_pinned_tab: "/images/apple-touch-icon.png"

    ShowBreadCrumbs: false
    ShowReadingTime: false
    ShowShareButtons: false
    ShowToc: false
    author: false
    hideFooter: true
    defaultTheme: dark